### ISSUE TITLE
Drawing annotations is slow

### ISSUE THREAD

**Issue by schukin** [Buglife/buglife-android#10]
`AnnotationView.onDraw` appears to be continuously redrawing the image/screenshot attachment when annotations are being drawn/changed. See e3aa710

**Comment by alexfu** [comment]
@schukin any chance you can provide a screen recording? I'm not 100% sure that I'm able to reproduce with the devices I have.

**Comment by schukin** [comment]
Turns out I'm unable to reproduce this anymore. False alarm – sorry everyone!
