### ISSUE TITLE
Buglife crashing when reporting crash via screenshot

### ISSUE THREAD

**Issue by shaii28** [Buglife/buglife-android#11]
buglife android sdk version 0.9.14 crashes when trying to report a bug via screenshot trigger 
on Android 6.0

Steps:
launch an app with the bug life android SDK 0.9.14
Take a screenshot
Press report a bug in the dialog
Click on the Arrow in the action bar

Expected result:
Bug is reported

Actual result:
buglife crashes

See exception log
[buglifecrash.txt](https://github.com/Buglife/buglife-android/files/1290447/buglifecrash.txt)

**Comment by alexfu** [comment]
@shaii28 the crash report says that the attachment type is `text/plain`, which is interesting because the SDK doesn't use that type for screenshots. I suspect you are you attaching your own files in addition to the screenshot?

**Comment by schukin** [comment]
Fixed in 57493b1; We'll issue a new release shortly. Thanks everyone!
