### ISSUE TITLE
Unable to manually stop screen recording on Android 7

### ISSUE THREAD

**Issue by schukin** [Buglife/buglife-android#12]
1. Tap "Record Screen" button in the example app
2. Allow screen recording to begin
3. Tap the red "Stop recording" button in the status bar

Expected result: Screen recording should stop, and ReportActivity should be presented.
Actual result: Tap event is captured at the OS level, which shows a notification tray hint animation.

This button seems to work fine in Android 6, oddly.

**Comment by alexfu** [comment]
@schukin Would you be open to using a floating button as a way to stop recording as opposed to having it in the status bar? A persistent notification could also work but I'm not too sure it'll be obvious to users.

**Comment by schukin** [comment]
@alexfu Absolutely! This is exactly what we had in mind. Any suggestions on the best way to go about doing this?

**Comment by alexfu** [comment]
@schukin I'm envisioning a small circular button that can be moved around and when clicked, it will stop the recording.

If this sounds good to you, I can start working on a prototype?

**Comment by schukin** [comment]
@alexfu that sounds ideal. 👌💯 By all means, go ahead!
