### ISSUE TITLE
Ask for permissions when do a snapshot

### ISSUE THREAD

**Issue by spinillos** [Buglife/buglife-android#13]
After set `Buglife.setInvocationMethod(InvocationMethod.SCREENSHOT)`, if the user don't want to accept the permission, it asks for it in every activity that the user opens. It's very annoying.

It could be fine if the `setInvocationMethod` only do that, set it; and ask for the permission when the user wants to report a bug.

**Comment by schukin** [comment]
Thanks for reporting this @spinillos! This has been fixed & released in Buglife Android v0.9.15.
