### ISSUE TITLE
Defer bug report processing

### ISSUE THREAD

**Issue by alexfu** [Buglife/buglife-android#18]
Currently, sending bug reports requires a network connection. If a network connection is not available, an error is thrown and the user will need to send the report again at a later time. 

This proposal is to allow the SDK to handle the deferment for the user so that even if there is no network connection, we will persist the request and try again later. 

This will consequently resolve #4 and also not require the user to stick around while the bug report is being uploaded.

**Comment by schukin** [comment]
Yes! Buglife iOS already does this; upon tapping "Send", the bug reporter UI is dismissed and the bug report is submitted asynchronously. If for whatever reason the report fails to send, then it is cached on the device storage & we re-attempt submission on the next "cold" application launch. (iOS applications are usually terminated by the OS ~10 minutes after they've been backgrounded)

I don't know if this same approach is appropriate for the Android application lifecycle... One approach we've considered is using local notifications when a report fails to send. (This would be ideal on iOS, except it isn't guaranteed that we have notification permissions.) @alexfu any ideas?

**Comment by alexfu** [comment]
@schukin Since Android 8.0, background services now have similar restrictions to iOS in that a background service will be killed after a certain period of time. 

The recommended way to handle long running tasks is to use the [JobScheduler](https://developer.android.com/topic/performance/scheduling.html#js) API. However, it is only available from API 21+.

I don't think dropping support for everything below API 21 is an option right now so JobScheduler is out.

Another recommended way is to use [Firebase JobDispatcher](https://developer.android.com/topic/performance/scheduling.html#fjd). Firebase JobDispatcher in a nutshell provides a backward compatible way to use JobScheduler

The upside to using Firebase JobDispatcher is that we get things like, retry and running jobs only when a network connection is available, for free. The downside is depending on a library and all of the things that comes with it. I'm hoping the downside is not too much of an issue in this case.

Let me know what you think.

**Comment by schukin** [comment]
Hmmm. We'd like to avoid bringing in additional dependencies if possible, since many SDK consumers are highly sensitive to this. And we take pride in shipping a lightweight SDK :)

Would it be possible to simply use JobScheduler when running Android 5+, and fall back to synchronous report submission on anything lower than 5?

**Comment by alexfu** [comment]
@schukin I think that's completely fine to begin with. I wasn't sure if feature parity was of a huge deal for all supported platforms. I'll go ahead and get started on that!
