### ISSUE TITLE
Crash on Oreo. 

### ISSUE THREAD

**Issue by oleshkevych** [Buglife/buglife-android#28]
Hi!
Got report from fabric from Pixel with android 8.

`Caused by java.lang.IllegalStateException: Not allowed to start service Intent { cmp=io.comgy.mgm_android.stage/com.buglife.sdk.reporting.SubmitReportLegacyService }: app is in background uid UidRecord{4a8e769 u0a90 CEM  idle procs:1 seq(0,0,0)}
       at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1505)
       at android.app.ContextImpl.startService(ContextImpl.java:1461)
       at android.content.ContextWrapper.startService(ContextWrapper.java:644)
       at com.buglife.sdk.reporting.SubmitReportLegacyService.start(SubmitReportLegacyService.java:58)
       at com.buglife.sdk.BugReporterImpl.<init>(BugReporterImpl.java:48)
       at com.buglife.sdk.Client$Builder.buildWithEmail(Client.java:282)
       at com.buglife.sdk.Buglife.initWithEmail(Buglife.java:67)`

Seems like some service is being started in background. This is not allowed in Oreo. Can you update logic for API level >= 26

**Comment by schukin** [comment]
Hi @oleshkevych - can you tell us which version of buglife-android you're using?

**Comment by oleshkevych** [comment]
Hey @schukin Thanks for quick reaction! :)
All that I have in the app
 ```
    implementation 'com.buglife.sdk:buglife-android:1.3.0'
    implementation 'com.android.volley:volley:1.0.0'
```
 ```
public class MyApplication extends Application {

    @Override
    public void onCreate() {
        super.onCreate();
        Fabric.with(this, new Crashlytics(), new CrashlyticsNdk());
        plantTimber();
        mRepositoryComponent = buildRepositoryComponent();
       
        Buglife.initWithApiKey(this, BuildConfig.BUGLIFE_API_KEY);
        Buglife.setInvocationMethod(InvocationMethod.SCREENSHOT);
    }
```

**Comment by alexfu** [comment]
@oleshkevych looks like the stacktrace doesn't match up with your code in `MyApplication`.

Last line of stacktrace references:

```
com.buglife.sdk.Buglife.initWithEmail(Buglife.java:67)
```

whereas in your code you do `Buglife.initWithApiKey`.

So it's possible this was happening on an older version of your app (and an older version of Buglife) but has since been resolved. Can you confirm this? I was unable to reproduce on my Pixel 2 w/ Oreo.

**Comment by oleshkevych** [comment]
@alexfu Sorry for this. You are right. Init method was changed after I reported this. But in general it should n't change anything, version wasn't changed. I faced this issue also on Pixel and think that there is something with starting service from background according to this: [link](https://developer.android.com/about/versions/oreo/background.html)

**Comment by silviahisham** [comment]
Same issue happened with me as well, reported on 3 oreo devices. Using Buglife 1.3.0
