### ISSUE TITLE
Theming not working

### ISSUE THREAD

**Issue by ghost** [Buglife/buglife-android#31]
I've added the following to my colors.xml file however it seems to not work.

The expected behaviour here is that it would change the color of the toolbar icons and text to the color specified however it just remains black. Is someone able to tell me if I've misunderstood or if there is a known way to change these colors?

`<color name="buglifeTextColorPrimary">@android:color/white</color>`

**Comment by danhd123** [comment]
Hi @Xenero, we're working on a fix now. Should be up in 1.3.1 shortly.
