### ISSUE TITLE
Unable to initialize Buglife. Dependency `com.android.volley:volley` not found.

### ISSUE THREAD

**Issue by balrampandey19** [Buglife/buglife-android#35]
can you guys please this issue asap. You had closed this issue but i am still getting this error on your latest release.

**Comment by schukin** [comment]
Hi @balrampandey19 - can you try downgrading to 1.2.4, and see if the error still occurs?

**Comment by balrampandey19** [comment]
Hi @schukin  i downgraded to 1.2.4 but i still getting same error.

**Comment by schukin** [comment]
This is fixed in Buglife 1.3.3.
