### ISSUE TITLE
Bug Button not showing

### ISSUE THREAD

**Issue by felipecastilhos** [Buglife/buglife-android#44]
I'm trying to setup the buglife in my project like this:
`            Buglife.initWithEmail(application, "random@email.com")
            Buglife.setInvocationMethod(InvocationMethod.BUG_BUTTON)`

But the button its not showing up.

Is some step that I skipped?

**Comment by schukin** [comment]
Hi @felipecastilhos - Apologies, the bug button isn't currently implemented on Android at the moment; that API shouldn't be exposed. Sorry for the confusion!

(For what it's worth, we generally recommend most apps to use the `SCREENSHOT` invocation, which comes more naturally to users. Although you may also implement your own custom invocation.)

**Comment by felipecastilhos** [comment]
Ok, thanks. We can close it for now.
