### ISSUE TITLE
Asking permission when starting the app

### ISSUE THREAD

**Issue by felipecastilhos** [Buglife/buglife-android#46]
I know this happens because I started the service on my application. But there is any way I could configure it to ask just when the user take the screenshot?

**Comment by schukin** [comment]
Unfortunately no; permissions are required to be able to detect screenshots to begin with.

I can suggest a couple workarounds:

* Start Buglife later on in your app lifecycle (i.e. after the user has made it through the sign-up flow)
* Add an option in your app's settings menu to either show the bug reporter directly, or to enable Buglife (thereby requesting permissions)
