### ISSUE TITLE
Volley must be explicitly added to build.gradle

### ISSUE THREAD

**Issue by schukin** [Buglife/buglife-android#48]
Buglife currently requires Android volley to be explicitly added to the host app's `build.gradle`. i.e.

```groovy
dependencies {
	implementation 'com.buglife.sdk:buglife-android:1.3.2'
	implementation 'com.android.volley:volley:1.1.0'
}
```

This is obviously sub-optimal; this issue is to track progress towards removing that step entirely, and allowing host apps to integrate Buglife with only a 1-line change to their `build.gradle`, i.e.

```groovy
dependencies {
	implementation 'com.buglife.sdk:buglife-android:1.3.2'
}
```

**Comment by schukin** [comment]
For posterity: when Volley is omitted from the host application, a crash occurs on launch (see #47, credit due to @samrombswm).

**Comment by alexfu** [comment]
@schukin just out of curiosity, how are you publishing to maven? as an experiment, i would try publishing to jitpack.io and compare the results.

**Comment by schukin** [comment]
Turns out this was caused by a missing dependency in the POM file. 🤦🏻‍♂️ (Thanks @danhd123 for getting to the bottom of this!)

buglife-android 1.3.3 has been released, which resolves this issue. Thanks @alexfu @samrombswm!
