### ISSUE TITLE
Move the summary field title to strings.xml

### ISSUE THREAD

**Issue by Sonphil** [Buglife/buglife-android#50]
I'm trying to localize the strings. However, the summary title is hardcoded [here](https://github.com/Buglife/buglife-android/blob/master/src/main/java/com/buglife/sdk/TextInputField.java#L69).

Can the title be moved to the strings resource file so that I can override it in my app?

**Comment by schukin** [comment]
Hi @Sonphil - can you submit a PR? Then we can merge it and ship a new build.
