### ISSUE TITLE
Any chance of replacing Volley with OKHttp?

### ISSUE THREAD

**Issue by R4md4c** [Buglife/buglife-android#55]
Any chance of replacing Volley's network stack with OKHttp which is considered a more modern and efficient alternative to Volley? 

I know that Volley can work together with OKHttp, but since probably most of the apps that I've seen uses OKHttp in one way or another (e.g Retrofit which uses OKHttp implicitly), devs won't need to explicitly add Volley as dependency.

**Comment by schukin** [comment]
Sure! Would you be opposed to submitting a pull request? We're not _super_ familiar with OKHttp, but it seems fine on the surface, so should be an easy merge. :)

**Comment by danhd123** [comment]
Merged in 1.4.3
