### ISSUE TITLE
Request: make including device location in report optional

### ISSUE THREAD

**Issue by timc-mediamonks** [Buglife/buglife-android#60]
Currently the `EnvironmentSnapshot` checks if COARSE or FINE location permission has been granted to the app and if so, it attempts to include a location in the report.

Given that 

- location data is extremely privacy sensitive. Collecting this data is subject to privacy laws depending on where you are. Also [apps that do this must have a privacy policy both in the play store and in the app itself](https://play.google.com/about/privacy-security-deception/user-data/personal-sensitive/).
- the SDK does this silently. If a user has granted location permission to an app because they are under the impression it needs that permission for a specific feature*, it's unfair to take advantage of that and not make it known.
- it is an undocumented feature.

I would urge to make this specific feature optional.

*I have an app that requires location permission to use BLE features. Because users are often reluctant to grant location permission for BLE features, the app tells the user it needs location just for that feature, and that it will never actually use the location data. Integrating the SDK as it currently functions would contradict that.

**Comment by danhd123** [comment]
Great point on privacy, I’ll see if we can get that into the next release. Thanks!

**Comment by danhd123** [comment]
Fixed in the v1.5.0 release, including a switch and better documentation. Thanks again!
