### ISSUE TITLE
P0: Cannot reply to bug reporters, emails gone.

### ISSUE THREAD

**Issue by duncancarroll** [Buglife/buglife-android#64]
BugLife library version 1.5.1
Client code calls the following code within `Application.onCreate()`:
```
Buglife.setUserEmail(userEmail)
Buglife.setUserIdentifier(userId)
```

Until very recently this worked as expected and email addresses showed up as expected in the BugLife web reporting interface, however today they are displaying only as userId's (see screenshot), which prevents us from replying to the user.  No changes to the client have been made. 

This is P0 as it negatively impacts user experience with our support staff.

**Comment by danhd123** [comment]
Hi Duncan, 

We're seeing other customers who are using the latest Buglife Android SDK and submitting bugs with both a user identifier and a user email without issues. Can you paste all of the Buglife-relevant lines of your `Application.onCreate()` (minus your API key, of course).

**Comment by duncancarroll** [comment]
I see what's going on here.  The value passed to `BugLife.setUserEmail()` is nullable, so if you set a null value it will remove that from the dashboard.  That explains what's happening, thanks.

I'll submit a PR to add that to the documentation.
