### ISSUE TITLE
Shake is too sensitive 

### ISSUE THREAD

**Issue by oferRounds** [Buglife/buglife-android#79]
We get complains from Android users that report popup comes up when they did not intended it to
Is there an option to make it less sensitive?

**Comment by oferRounds** [comment]
hi @schukin 
Any idea how to solve this issue?

**Comment by ioviov** [comment]
The same problem : (
Please help us

**Comment by schukin** [comment]
This is now resolved in v1.5.3. Thanks everyone!

**Comment by oferRounds** [comment]
Hi @schukin 
Can you update also the React Native repo?

**Comment by oferRounds** [comment]
@schukin it seems the shake is still too sensitive, we keep getting complains from users :\
